### ISSUE TITLE
Allow for multiple landing zone deployments per organization (dev/stg/prod) - start with global organization policies

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#92] opened 2022-05-19 14:08 UTC
Need a way to run at least 2 LZ deployments per org - one stable, one for dev

see https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/27#issuecomment-1131708544

<img width="1423" alt="Screen Shot 2022-05-19 at 9 50 22 AM" src="https://user-images.githubusercontent.com/94715080/169309502-d8ae2a01-15dc-4014-b888-b8d752759824.png">

For common - as expected - we need to handle running the org policies once for multiple landing zones - or ignore reset errors
<img width="1431" alt="Screen Shot 2022-05-19 at 9 58 33 AM" src="https://user-images.githubusercontent.com/94715080/169311334-7cdd4dc6-b263-4225-987d-03c0a5d24b4a.png">

Fix one of the global bucket names and make org policies optional
```
tep #3 - "tf apply": module.core-guardrails.module.guardrails[0].google_cloudfunctions_function_iam_member.guardrails_export_asset_inventory_invoker: Creation complete after 5s [id=projects/orpe-or-guardrailsor2/locations/northamerica-northeast1/functions/OrPeCPS-GuardrailsExportAssetInventory-cf/roles/cloudfunctions.invoker/serviceAccount:orpecld-guardrails-sa@orpe-or-guardrailsor2.iam.gserviceaccount.com]
Step #3 - "tf apply": ╷
Step #3 - "tf apply": │ Error: googleapi: Error 409: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again., conflict
Step #3 - "tf apply": │ 
Step #3 - "tf apply": │   with module.core-audit-bunker.google_storage_bucket.log-bucket,
Step #3 - "tf apply": │   on ../../modules/audit-bunker/main.tf line 61, in resource "google_storage_bucket" "log-bucket":
Step #3 - "tf apply": │   61: resource "google_storage_bucket" "log-bucket" {
Step #3 - "tf apply": │ 
Step #3 - "tf apply": ╵
Step #3 - "tf apply": ╷
Step #3 - "tf apply": │ Error: Error creating AccessPolicy: googleapi: Error 409: Policy already exists with parent organizations/843157297140
Step #3 - "tf apply": │ 
Step #3 - "tf apply": │   with module.access-context-manager.google_access_context_manager_access_policy.access_policy[0],
Step #3 - "tf apply": │   on ../../modules/vpc-service-controls/main.tf line 9, in resource "google_access_context_manager_access_policy" "access_policy":
Step #3 - "tf apply": │    9: resource "google_access_context_manager_access_policy" "access_policy" {
Step #3 - "tf apply": │ 
Step #3 - "tf apply": ╵


audit-bunker main.tf
resource "google_storage_bucket" "log-bucket" {

```

rename and disable
```

audit_streams = {
    prod = {
      bucket_name          = "auditor2" 
      
common build
Error: Error creating AccessPolicy: googleapi: Error 409: Policy already exists with parent organizations/843157297140
│ 
│   with module.access-context-manager.google_access_context_manager_access_policy.access_policy[0],
│   on ../../modules/vpc-service-controls/main.tf line 9, in resource "google_access_context_manager_access_policy" "access_policy":
│ 

turn off duplicate policies
michael@cloudshell:~/landingzone-co2/pbmm-on-gcp-onboarding/environments/bootstrap (landingzone-co2)$ git diff
diff --git a/environments/common/common.auto.tfvars b/environments/common/common.auto.tfvars
index 65eb9f7..3bd2833 100644
--- a/environments/common/common.auto.tfvars
+++ b/environments/common/common.auto.tfvars
@@ -6,7 +6,7 @@

 org_policies = {
   directory_customer_id = []
-  policy_boolean        = { "constraints/compute.skipDefaultNetworkCreation" = true, "constraints/compute.disableSerialPortAccess" = true } #constraints/compute.skipDefaultNetworkCreation = false
+  policy_boolean        = {}# "constraints/compute.skipDefaultNetworkCreation" = true, "constraints/compute.disableSerialPortAccess" = true } #constraints/compute.skipDefaultNetworkCreation = false
   policy_list           = {}
   setDefaultPolicy      = false # leave false for testing


override empty id defaults in common
michael@cloudshell:~/landingzone-co2/pbmm-on-gcp-onboarding/environments/bootstrap (landingzone-co2)$ git diff
diff --git a/environments/common/common.auto.tfvars b/environments/common/common.auto.tfvars
index 3bd2833..553a02b 100644
--- a/environments/common/common.auto.tfvars
+++ b/environments/common/common.auto.tfvars
@@ -38,8 +38,8 @@ folders = {


 access_context_manager = { # REQUIRED OBJECT. VPC Service Controls object.
-  policy_name         = "" # OPTIONAL EDIT. If null, will be generated by module. Only used when creating new policy.
-  policy_id           = "" # OPTIONAL EDIT. Only used when previously existing. Includes subsequent runs 
+  policy_name         = "or" # OPTIONAL EDIT. If null, will be generated by module. Only used when creating new policy.
+  policy_id           = "or2" # OPTIONAL EDIT. Only used when previously existing. Includes subsequent runs 
   user_defined_string = "oracm" # Optional EDIT.
   access_level        = {} # leave empty for testing

```

ok

<img width="1430" alt="Screen Shot 2022-05-19 at 12 36 55 PM" src="https://user-images.githubusercontent.com/94715080/169352574-913882cd-14c6-4815-a9e4-732373ff8c28.png">

**Comment by obriensystems** [comment] 2024-04-08 01:18
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4

**Comment by obriensystems** [comment] 2024-04-08 01:19
duplicate of #240

**Closed by obriensystems** 2024-04-08 01:19 UTC
Labels: documentation, enhancement, 2024-pre-tef-v4
