### ISSUE TITLE
Blueprints backports/sync

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pbmm-on-gcp-onboarding#46] opened 2022-04-06 19:51 UTC
https://github.com/GoogleCloudPlatform/blueprints/blob/main/catalog/landing-zone/policies/folder-naming-constraint-template.yaml#L22

# links

https://cloud.google.com/docs/security/infrastructure/design
https://cloud.google.com/architecture/security-foundations

**Comment by obriensystems** [comment] 2024-04-08 01:24
20240406: Closing issue during retrofit/rebase of this TEF V1 based/modified repo to TEF V4 standards
This issue may participate in the LZ refactor after rebase
Query on all issues related to the older V1 version via the tag
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/labels/2024-pre-tef-v4

**Comment by obriensystems** [comment] 2024-04-08 01:45
duplicate of #360

**Closed by obriensystems** 2024-04-08 01:45 UTC
Labels: tef, 2024-pre-tef-v4
